// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iivaqldpquzqsgupvlfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdmFxbGRwcXV6cXNndXB2bGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzgwNjksImV4cCI6MjA3MjQ1NDA2OX0.E61Cvun9toTJs0f9jeBKi0tWID3r3Kqb3AYRe_ig6UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});